from pathlib import Path
import re

p=Path('client-admin-premium.js')
s=p.read_text()
orig=s

# 1) Four internal areas: Progreso, Alimentación, Rutina, Seguimiento.
s=s.replace('grid-template-columns:repeat(5,minmax(0,1fr))','grid-template-columns:repeat(4,minmax(0,1fr))')
s=s.replace('.dcc-ca-tab-ico{display:block;margin:0 auto 3px;font-size:15px;line-height:1}', '.dcc-ca-tab-ico{display:grid;place-items:center;height:18px;margin:0 auto 3px;font-size:15px;line-height:1}.dcc-ca-tab-ico svg{width:18px;height:18px;display:block}')

# 2) Restore plan-oriented Alimentacion view. Editing remains inside the client only when requested.
food_new=r'''function dietPlanComplete(id){const d=data?.diets?.[id]||{};const types=['training','rest'];return types.every(t=>{const ms=Array.isArray(d?.[t]?.meals)?d[t].meals:[];return ms.length>0&&ms.every(m=>normalizeOptions(m).some(o=>Array.isArray(o.foods)&&o.foods.length>0))})}
function foodEditor(id){const t=window.__dccDietType||'training',d=data?.diets?.[id]?.[t]||{meals:[]},ms=Array.isArray(d.meals)?d.meals:[],open=Number.isInteger(window.__dccDietOpenMeal)?window.__dccDietOpenMeal:null,map=window.__dccDietOptionMap||{},avoid=avoidText(c(id));return`${avoid?`<section class="dcc-ca-card dcc-native-avoid-warning"><div class="dcc-ca-title"><h2>Aviso del cliente</h2></div><div style="margin-top:8px;color:#e8e5de;font-size:11px;line-height:1.45">No incluir en la alimentación: <b style="color:${G2}">${esc(avoid)}</b>.</div></section>`:''}<div class="dcc-diet-switch"><button class="${t==='training'?'active':''}" onclick="__dccDietType='training';dccClientAdmin('${id}','food')">Día de entrenamiento</button><button class="${t==='rest'?'active':''}" onclick="__dccDietType='rest';dccClientAdmin('${id}','food')">Día de descanso</button></div><div class="dcc-diet-caption"><b>Alimentación</b><span>Toca una comida para editarla</span></div><div class="dcc-diet-meals">${ms.map((m,i)=>mealHtml(id,t,m,i,open===i,map[i]||0)).join('')||'<div class="dcc-diet-empty">Todavía no hay comidas configuradas.</div>'}</div><button class="dcc-diet-add-meal" onclick="dccDietAddMeal('${id}','${t}')">＋ Añadir comida</button><button class="dcc-tr-cancel" style="width:100%;margin-top:8px" onclick="dccFinishDietEdit('${id}')">Volver al plan</button>`}
function foodPane(id){if(window.__dccDietEditing)return foodEditor(id);const d=data?.diets?.[id]||{},training=Array.isArray(d?.training?.meals)?d.training.meals:[],rest=Array.isArray(d?.rest?.meals)?d.rest.meals:[],has=training.length>0||rest.length>0,done=dietPlanComplete(id),status=!has?'Sin plan':done?'Plan terminado':'Plan sin terminar';return`<section class="dcc-ca-card"><div class="dcc-ca-title"><h2>Plan de alimentación</h2><span class="pill">${esc(status)}</span></div><div style="margin-top:12px;display:grid;grid-template-columns:1fr 1fr;gap:8px"><div class="dcc-ca-activity-item"><small>Día de entrenamiento</small><b>${training.length} comidas</b></div><div class="dcc-ca-activity-item"><small>Día de descanso</small><b>${rest.length} comidas</b></div></div><div class="dcc-ca-summary-actions" style="margin-top:12px"><button class="dcc-ca-action-secondary" onclick="dccEditDietPlan('${id}')">Editar plan</button><button class="dcc-ca-action-primary" onclick="dccNewDietPlan('${id}')">Nuevo plan</button></div></section>`}
function mealHtml'''
s,n=re.subn(r'function foodPane\(id\)\{.*?\}function mealHtml',food_new,s,flags=re.S)
assert n==1, f'foodPane replacement count={n}'

# 3) Routine keeps all days collapsed, with the old two clear actions underneath.
training_new=r'''function trainingPane(id){const ds=routineDays(id),edit=!!window.__dccTrainingEdit;if(window.__dccTrainingOpen!==null&&!Number.isInteger(window.__dccTrainingOpen))window.__dccTrainingOpen=null;const status=ds.length?`${ds.length} ${ds.length===1?'día':'días'} configurados`:'Sin rutina';return`<section class="dcc-ca-card" style="margin-top:0"><div class="dcc-ca-title"><h2>Plan de entrenamiento</h2><span class="pill">${esc(status)}</span></div></section><div class="dcc-tr-days" style="margin-top:10px">${ds.map((d,i)=>trainingDay(id,d,i,window.__dccTrainingOpen===i,edit)).join('')||'<div class="dcc-diet-empty">Este cliente todavía no tiene una rutina asignada.</div>'}</div>${edit?`<div class="dcc-tr-actions"><button class="dcc-tr-cancel" onclick="dccCancelRoutine('${id}')">Cancelar</button><button class="dcc-tr-save" onclick="dccSaveRoutine('${id}')">Guardar cambios</button></div>`:`<div class="dcc-tr-actions"><button class="dcc-tr-edit" style="width:100%" onclick="dccModifyRoutine('${id}')">✎ &nbsp; Editar rutina</button><button class="dcc-tr-new" style="margin:0" onclick="dccCreateRoutine('${id}')">＋ &nbsp; Crear nueva rutina</button></div>`}`}
function trainingDay'''
s,n=re.subn(r'function trainingPane\(id\)\{.*?\}function trainingDay',training_new,s,flags=re.S)
assert n==1, f'trainingPane replacement count={n}'

# 4) First tab is Progreso. No fake photo placeholders: until real photos exist, show a compact empty state.
summary_new=r'''function summaryPane(id,cl,m){return `<div class="dcc-ca-summary"><section class="dcc-ca-card dcc-ca-evolution"><div class="dcc-ca-section-head"><h2>Evolución física</h2></div><div style="margin-top:12px;padding:14px 12px;border:1px solid rgba(217,170,74,.24);border-radius:13px;text-align:center"><b style="display:block;font-size:12px">Todavía no hay fotos</b><span style="display:block;margin-top:5px;color:#8f98a3;font-size:9px;line-height:1.4">Cuando llegue el check-in fotográfico mensual aparecerán aquí espalda, frente y lateral.</span></div><div class="dcc-ca-next-photo"><span>▣</span><span><b>Check-in fotográfico</b><br>3 fotos · espalda, frente y lateral · 1 vez al mes</span></div></section><section class="dcc-ca-card"><div class="dcc-ca-section-head"><h2>Progreso</h2></div><div class="dcc-ca-grid">${info('Peso inicial',m.initial.toFixed(1).replace('.',',')+' kg')}${info('Peso actual',m.current.toFixed(1).replace('.',',')+' kg')}${info('Grasa inicial',m.fi!=null?m.fi.toFixed(1).replace('.',',')+' %':'—')}${info('Grasa actual',m.fc!=null?m.fc.toFixed(1).replace('.',',')+' %':'—')}</div></section><section class="dcc-ca-card dcc-ca-data-card"><div class="dcc-ca-section-head"><h2>Datos principales</h2><button class="dcc-ca-link" onclick="dccClientEdit('${id}')">✎ Editar</button></div><div class="dcc-ca-grid">${info('Edad',clientAge(cl))}${info('Altura',clientHeight(cl))}${info('Objetivo',esc(cl.goal||'—'))}${info('Último check-in',lastCheckin(id))}${info('Alimentos a evitar',esc(avoidText(cl)||'Sin alimentos indicados'))}</div></section><div class="dcc-ca-danger-row"><button class="dcc-ca-action-secondary" onclick="dccClientEdit('${id}')">Editar cliente</button><button class="dcc-ca-delete" onclick="dccLegacyDelete('${id}')">Eliminar cliente</button></div></div>`}'''
s,n=re.subn(r'function summaryPane\(id,cl,m\)\{.*?\}\nfunction editPane',summary_new+'\nfunction editPane',s,flags=re.S)
assert n==1, f'summaryPane replacement count={n}'

# 5) Rebuild internal navigation with the original Alimentacion and dumbbell icons.
nav_new=r'''<nav class="dcc-ca-tabs"><button class="dcc-ca-tab ${tab==='summary'?'active':''}" onclick="dccOpenClientTab('${id}','summary')"><span class="dcc-ca-tab-ico"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 19V5"/><path d="M4 19h16"/><path d="m7 15 4-4 3 2 5-6"/></svg></span><span class="dcc-ca-tab-label">Progreso</span></button><button class="dcc-ca-tab ${tab==='food'?'active':''}" onclick="dccOpenClientTab('${id}','food')"><span class="dcc-ca-tab-ico"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M7 3v7"/><path d="M4.5 3v5.5A2.5 2.5 0 0 0 7 11a2.5 2.5 0 0 0 2.5-2.5V3"/><path d="M7 11v10"/><path d="M16 3v18"/><path d="M16 3c3 1.5 3 5 0 7"/></svg></span><span class="dcc-ca-tab-label">Alimentación</span></button><button class="dcc-ca-tab ${tab==='training'?'active':''}" onclick="dccOpenClientTab('${id}','training')"><span class="dcc-ca-tab-ico"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 9v6"/><path d="M7 7v10"/><path d="M17 7v10"/><path d="M20 9v6"/><path d="M7 12h10"/><path d="M4 12H2"/><path d="M22 12h-2"/></svg></span><span class="dcc-ca-tab-label">Rutina</span></button><button class="dcc-ca-tab ${tab==='followup'?'active':''}" onclick="dccOpenClientTab('${id}','followup')"><span class="dcc-ca-tab-ico"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="5" y="4" width="14" height="17" rx="2"/><path d="M8 11l2 2 5-5M8 17h7"/></svg></span><span class="dcc-ca-tab-label">Seguimiento</span></button></nav>'''
s,n=re.subn(r'<nav class="dcc-ca-tabs">.*?</nav>',nav_new,s,count=1,flags=re.S)
assert n==1, f'nav replacement count={n}'

# Progress legacy route now lands on the new first Progreso tab.
s=s.replace("window.dccOpenClientTab=(id,tab)=>{if(tab==='training')window.__dccTrainingOpen=null;render(id,tab)};", "window.dccOpenClientTab=(id,tab)=>{if(tab==='progress')tab='summary';if(tab==='training')window.__dccTrainingOpen=null;if(tab!=='food')window.__dccDietEditing=false;render(id,tab)};")

# Diet actions. New plan reuses the existing full Alimentacion generator; edit stays compact in client.
anchor="window.dccClientEdit=id=>render(id,'edit');"
insert="window.dccEditDietPlan=id=>{window.__dccDietEditing=true;window.__dccDietOpenMeal=null;render(id,'food')};window.dccFinishDietEdit=id=>{window.__dccDietEditing=false;window.__dccDietOpenMeal=null;render(id,'food')};window.dccNewDietPlan=id=>{window.__dccDietEditing=false;window.selectedClient=id;if(typeof showCoach==='function')showCoach('diets')};\n"
assert anchor in s
s=s.replace(anchor,insert+anchor,1)

if s==orig: raise SystemExit('No changes made')
p.write_text(s)
print('patched client-admin-premium.js')
