from pathlib import Path

def rep(path, old, new, count=1):
    p=Path(path); s=p.read_text()
    if old not in s:
        raise SystemExit(f'PATTERN NOT FOUND in {path}: {old[:120]!r}')
    s=s.replace(old,new,count)
    p.write_text(s)

# 1) Coach bottom navigation: only Panel / Clientes / Calendario.
p='coach-premium-core-v9.js'
rep(p,".dcc-cl-tools{display:grid;grid-template-columns:1fr 48px;gap:9px}",".dcc-cl-tools{display:grid;grid-template-columns:1fr;gap:9px}")
rep(p,"main.innerHTML=`<div class=\"dcc-cl\"><header class=\"dcc-cl-head\"><div><h1>Clientes</h1><p>Gestiona el proceso de cada persona.</p></div><button class=\"dcc-cl-new\" onclick=\"newClient()\">＋ Nuevo cliente</button></header><div class=\"dcc-cl-tools\"><label class=\"dcc-cl-search\">⌕<input id=\"dccClientSearch\" placeholder=\"Buscar cliente...\" oninput=\"window.dccFilterClients()\"></label><button class=\"dcc-cl-filter\" onclick=\"toast('Filtros próximamente')\">▽</button></div><div class=\"dcc-cl-subtools\"><div class=\"dcc-cl-tabs\"><button class=\"dcc-cl-tab active\" onclick=\"window.dccClientTab('all',this)\">Todos</button><button class=\"dcc-cl-tab\" onclick=\"window.dccClientTab('pending',this)\">Pendientes por revisar</button></div><button class=\"dcc-cl-sort\" onclick=\"window.dccSortClients()\">↕ &nbsp; A-Z⌄</button></div><div class=\"dcc-cl-list\" id=\"dccClientList\">${cs.map(clientCard).join('')||'<div class=\"dcc-cl-empty\">Todavía no hay clientes.</div>'}</div></div>`;\n    window.__dccClientMode='all';window.__dccClientSort='az';",
"main.innerHTML=`<div class=\"dcc-cl\"><header class=\"dcc-cl-head\"><div><h1>Clientes</h1><p>Gestiona y acompaña su progreso.</p></div><button class=\"dcc-cl-new\" onclick=\"newClient()\">＋ Nuevo cliente</button></header><div class=\"dcc-cl-tools\"><label class=\"dcc-cl-search\">⌕<input id=\"dccClientSearch\" placeholder=\"Buscar cliente...\" oninput=\"window.dccFilterClients()\"></label></div><div class=\"dcc-cl-subtools\"><span style=\"font-size:10px;font-weight:800;color:#8d96a1;letter-spacing:.7px\">CLIENTES ACTIVOS</span><button class=\"dcc-cl-sort\" onclick=\"window.dccSortClients()\">↕ &nbsp; A-Z⌄</button></div><div class=\"dcc-cl-list\" id=\"dccClientList\">${cs.map(clientCard).join('')||'<div class=\"dcc-cl-empty\">Todavía no hay clientes.</div>'}</div></div>`;\n    window.__dccClientMode='all';window.__dccClientSort='az';")
rep(p,"window.dccFilterClients=function(){const q=(document.getElementById('dccClientSearch')?.value||'').toLowerCase();document.querySelectorAll('.dcc-cl-card').forEach(x=>x.style.display=(x.dataset.name.includes(q)&&(window.__dccClientMode!=='pending'||x.dataset.pending==='1'))?'grid':'none')};",
"window.dccFilterClients=function(){const q=(document.getElementById('dccClientSearch')?.value||'').toLowerCase();document.querySelectorAll('.dcc-cl-card').forEach(x=>x.style.display=x.dataset.name.includes(q)?'grid':'none')};")
rep(p,"function navHtml(){return `<button onclick=\"showCoach('dashboard')\">${icon('panel')}<span>Panel</span></button><button onclick=\"showCoach('clients')\">${icon('clients')}<span>Clientes</span></button><button onclick=\"showCoach('calendar')\">${icon('calendar')}<span>Calendario</span></button><button onclick=\"showCoach('checkins')\">${icon('check')}<span>Check-in</span></button><button onclick=\"showCoach('messages')\">${icon('msg')}<span>Mensajes</span></button>`}\n  function enforceNav(){const n=document.getElementById('coach-nav');if(!n)return;const wanted=['Panel','Clientes','Calendario','Check-in','Mensajes'],labels=[...n.querySelectorAll('button span')].map(x=>x.textContent.trim());if(labels.length!==5||wanted.some((x,i)=>labels[i]!==x))n.innerHTML=navHtml();n.style.setProperty('grid-template-columns','repeat(5,minmax(0,1fr))','important')}\n  function active(screen){const n=document.getElementById('coach-nav');if(!n)return;const map={dashboard:0,clients:1,calendar:2,checkins:3,messages:4};n.querySelectorAll('button').forEach(x=>x.classList.remove('active'));const i=map[screen];if(i!==undefined)n.querySelectorAll('button')[i]?.classList.add('active')}",
"function navHtml(){return `<button onclick=\"showCoach('dashboard')\">${icon('panel')}<span>Panel</span></button><button onclick=\"showCoach('clients')\">${icon('clients')}<span>Clientes</span></button><button onclick=\"showCoach('calendar')\">${icon('calendar')}<span>Calendario</span></button>`}\n  function enforceNav(){const n=document.getElementById('coach-nav');if(!n)return;const wanted=['Panel','Clientes','Calendario'],labels=[...n.querySelectorAll('button span')].map(x=>x.textContent.trim());if(labels.length!==3||wanted.some((x,i)=>labels[i]!==x))n.innerHTML=navHtml();n.style.setProperty('grid-template-columns','repeat(3,minmax(0,1fr))','important')}\n  function active(screen){const n=document.getElementById('coach-nav');if(!n)return;const map={dashboard:0,clients:1,calendar:2,checkins:1,messages:1};n.querySelectorAll('button').forEach(x=>x.classList.remove('active'));const i=map[screen];if(i!==undefined)n.querySelectorAll('button')[i]?.classList.add('active')}")

# 2) Client detail becomes the hub. No training activity card; Check-in + Messages live in Seguimiento.
p='client-admin-premium.js'
rep(p,".dcc-ca-tabs{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));", ".dcc-ca-tabs{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));")
rep(p,"<button class=\"dcc-ca-tab ${tab==='summary'?'active':''}\" onclick=\"dccClientAdmin('${id}','summary')\">Resumen</button><button class=\"dcc-ca-tab ${tab==='food'?'active':''}\" onclick=\"dccClientAdmin('${id}','food')\">Alimentación</button><button class=\"dcc-ca-tab ${tab==='training'?'active':''}\" onclick=\"dccClientAdmin('${id}','training')\">Entrenamiento</button><button class=\"dcc-ca-tab ${tab==='progress'?'active':''}\" onclick=\"dccClientAdmin('${id}','progress')\">Progreso</button>",
"<button class=\"dcc-ca-tab ${tab==='summary'?'active':''}\" onclick=\"dccClientAdmin('${id}','summary')\">Resumen</button><button class=\"dcc-ca-tab ${tab==='food'?'active':''}\" onclick=\"dccClientAdmin('${id}','food')\">Dieta</button><button class=\"dcc-ca-tab ${tab==='training'?'active':''}\" onclick=\"dccClientAdmin('${id}','training')\">Rutina</button><button class=\"dcc-ca-tab ${tab==='progress'?'active':''}\" onclick=\"dccClientAdmin('${id}','progress')\">Progreso</button><button class=\"dcc-ca-tab ${tab==='followup'?'active':''}\" onclick=\"dccClientAdmin('${id}','followup')\">Seguimiento</button>")
anchor="function render(id,tab='summary'){"
follow="""function monthlyPhotoText(id){const x=data?.checkins?.[id]||{},raw=x.sentAt??x.sent_at??x.created_at??null;if(!raw)return'Pendiente · 3 fotos';const d=new Date(raw);if(!Number.isFinite(d.getTime()))return'Pendiente · 3 fotos';const next=new Date(d);next.setMonth(next.getMonth()+1);return next<=new Date()?'Pendiente · 3 fotos':`Próximo · ${next.toLocaleDateString('es-ES',{day:'numeric',month:'short'})}`}
function followupPane(id){const x=data?.checkins?.[id]||{},has=!!(x.sentAt||x.sent_at||x.created_at||x.updated_at);return `<section class=\"dcc-ca-card\"><div class=\"dcc-ca-title\"><h2>Seguimiento</h2><span style=\"font-size:9px;color:#8f98a3\">Todo en un solo lugar</span></div><div style=\"display:grid;gap:8px;margin-top:12px\"><button class=\"dcc-ca-detail\" style=\"width:100%;min-height:52px;text-align:left;padding:10px 13px\" onclick=\"${has?`window.__dccCheckinReturnClient='${id}';reviewCheckin('${id}')`:`toast('Todavía no hay un check-in enviado')`}\"><b style=\"display:block;font-size:12px\">Check-in semanal</b><span style=\"display:block;margin-top:4px;font-size:9px;opacity:.72\">${has?esc(lastCheckin(id)):'Sin check-in enviado'}</span></button><div style=\"padding:12px 13px;border:1px solid rgba(217,170,74,.32);border-radius:14px\"><b style=\"font-size:12px\">Check-in fotográfico mensual</b><div style=\"margin-top:5px;color:#8f98a3;font-size:9px\">3 fotos: espalda · frente · lateral</div><div style=\"margin-top:7px;color:${G2};font-size:10px;font-weight:800\">${esc(monthlyPhotoText(id))}</div></div><button class=\"dcc-ca-detail\" style=\"width:100%;min-height:52px;text-align:left;padding:10px 13px\" onclick=\"dccOpenClientChat('${id}')\"><b style=\"display:block;font-size:12px\">Mensajes</b><span style=\"display:block;margin-top:4px;font-size:9px;opacity:.72\">Abrir conversación con el cliente →</span></button></div></section>`}
window.dccOpenClientChat=function(id){window.__dccChatReturnClient=String(id);if(typeof window.dccOpenChat==='function')window.dccOpenChat(id)};
"""
rep(p,anchor,follow+anchor)
old="function pane(id,t,cl,m){if(t==='food')return foodPane(id);if(t==='training')return trainingPane(id);if(t==='progress')return`<section class=\"dcc-ca-card\"><div class=\"dcc-ca-title\"><h2>Progreso</h2></div><div class=\"dcc-ca-grid\">${info('Peso inicial',m.initial.toFixed(1).replace('.',',')+' kg')}${info('Peso actual',m.current.toFixed(1).replace('.',',')+' kg')}${info('Grasa inicial',m.fi!=null?m.fi.toFixed(1).replace('.',',')+' %':'—')}${info('Grasa actual',m.fc!=null?m.fc.toFixed(1).replace('.',',')+' %':'—')}</div></section>`;const ss=workouts30(id);return`<section class=\"dcc-ca-card\"><div class=\"dcc-ca-title\"><h2>Información general</h2></div><div class=\"dcc-ca-grid\">${info('Objetivo',esc(cl.goal||'—'))}${info('Edad',clientAge(cl))}${info('Altura',clientHeight(cl))}${info('Último check-in',lastCheckin(id))}${info('Alimentos a evitar',esc(avoidText(cl)||'Sin alimentos indicados'))}</div></section><section class=\"dcc-ca-card\"><div class=\"dcc-ca-activity-head\"><h2>Actividad de entrenamiento</h2><button class=\"dcc-ca-detail\" onclick=\"dccClientAdmin('${id}','training')\">Ver entrenamiento →</button></div><div class=\"dcc-ca-activity\"><div class=\"dcc-ca-activity-item\"><small>Últimos 30 días</small><b>${ss.length} sesiones</b></div><div class=\"dcc-ca-activity-item\"><small>Última sesión</small><b>${lastWorkout(id)}</b></div></div></section><button class=\"dcc-ca-delete\" onclick=\"dccLegacyDelete('${id}')\">Eliminar cliente</button>`}"
new="function pane(id,t,cl,m){if(t==='food')return foodPane(id);if(t==='training')return trainingPane(id);if(t==='progress')return`<section class=\"dcc-ca-card\"><div class=\"dcc-ca-title\"><h2>Progreso</h2></div><div class=\"dcc-ca-grid\">${info('Peso inicial',m.initial.toFixed(1).replace('.',',')+' kg')}${info('Peso actual',m.current.toFixed(1).replace('.',',')+' kg')}${info('Grasa inicial',m.fi!=null?m.fi.toFixed(1).replace('.',',')+' %':'—')}${info('Grasa actual',m.fc!=null?m.fc.toFixed(1).replace('.',',')+' %':'—')}</div></section>`;if(t==='followup')return followupPane(id);return`<section class=\"dcc-ca-card\"><div class=\"dcc-ca-title\"><h2>Información general</h2></div><div class=\"dcc-ca-grid\">${info('Objetivo',esc(cl.goal||'—'))}${info('Edad',clientAge(cl))}${info('Altura',clientHeight(cl))}${info('Último check-in',lastCheckin(id))}${info('Alimentos a evitar',esc(avoidText(cl)||'Sin alimentos indicados'))}</div></section>`}"
rep(p,old,new)

# 3) Actions are deterministic: Editar + Eliminar side by side at the bottom of Resumen.
p='client-edit-visibility-v1.js'
rep(p,"const del=[...r.querySelectorAll('button')].find(x=>norm(x.textContent)==='eliminar cliente');const box=document.createElement('div');box.className='dcc-summary-actions-final';const edit=document.createElement('button');edit.type='button';edit.className='dcc-ca-edit-client';edit.textContent='Editar cliente';edit.onclick=open;box.appendChild(edit);if(del)box.appendChild(del);wrap.appendChild(box);",
"const box=document.createElement('div');box.className='dcc-summary-actions-final';const edit=document.createElement('button');edit.type='button';edit.className='dcc-ca-edit-client';edit.textContent='Editar cliente';edit.onclick=open;const del=document.createElement('button');del.type='button';del.className='dcc-ca-delete';del.textContent='Eliminar cliente';del.onclick=()=>window.dccLegacyDelete?.(id);box.appendChild(edit);box.appendChild(del);wrap.appendChild(box);")

# 4) Chat and check-in launched from a client return to that client, not to removed global tabs.
p='messages-premium.js'
rep(p,"function navActive(){const n=document.getElementById('coach-nav');if(!n)return;n.querySelectorAll('button').forEach((b,i)=>b.classList.toggle('active',i===4))}",
"function navActive(){const n=document.getElementById('coach-nav');if(!n)return;n.querySelectorAll('button').forEach((b,i)=>b.classList.toggle('active',i===1))}")
rep(p,"window.dccCloseChat=function(){window.__dccOpenChat=null;renderMessages()};",
"window.dccCloseChat=function(){window.__dccOpenChat=null;const id=window.__dccChatReturnClient;if(id&&typeof window.dccClientAdmin==='function'){window.__dccChatReturnClient=null;window.dccClientAdmin(id,'followup');return}renderMessages()};")

p='checkin-premium.js'
rep(p,"window.dccMarkCheckinReviewed=function(id){const d=getData(),x=d?.checkins?.[id];if(!x)return;x.reviewed=true;x.reviewedAt=new Date().toISOString();try{if(typeof saveData==='function')saveData()}catch(e){console.error(e)}closeReview();window.__dccCheckinMode='reviewed';renderCheckins()};",
"window.dccMarkCheckinReviewed=function(id){const d=getData(),x=d?.checkins?.[id];if(!x)return;x.reviewed=true;x.reviewedAt=new Date().toISOString();try{if(typeof saveData==='function')saveData()}catch(e){console.error(e)}closeReview();if(window.__dccCheckinReturnClient&&typeof window.dccClientAdmin==='function'){const back=window.__dccCheckinReturnClient;window.__dccCheckinReturnClient=null;window.dccClientAdmin(back,'followup');return}window.__dccCheckinMode='reviewed';renderCheckins()};")

print('Client hub restructure applied')
