/* DCC — Panel + Clientes premium + navegación global estable */
(function(){
  'use strict';
  const GOLD="#d9aa4a", GOLD2="#f0c96b";
  const esc=v=>String(v??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[ch]));

  function injectCss(){
    if(document.getElementById("dcc-premium-v6")) return;
    document.getElementById("dcc-premium-v5")?.remove();
    const s=document.createElement("style");
    s.id="dcc-premium-v6";
    s.textContent=`
      #coach-main.dcc-premium-dashboard,#coach-main.dcc-premium-clients{
        background:
          radial-gradient(circle at 88% 3%,rgba(217,170,74,.07),transparent 25%),
          linear-gradient(180deg,#080a0d 0%,#050709 100%)!important;
        padding:10px 12px 92px!important;
        color:#f6f3ed!important;
      }
      .dcc-pd,.dcc-cl{max-width:980px;margin:auto}.dcc-pd *,.dcc-cl *{box-sizing:border-box}

      .dcc-pd-hero{position:relative;overflow:hidden;min-height:156px;padding:20px 19px 18px;border:1px solid rgba(217,170,74,.48);border-radius:24px;background:radial-gradient(circle at 88% 16%,rgba(240,201,107,.15),transparent 25%),linear-gradient(140deg,#10151a 0%,#090d11 56%,#080909 100%);box-shadow:inset 0 1px 0 rgba(255,255,255,.035),0 18px 38px rgba(0,0,0,.25)}
      .dcc-pd-hero:before,.dcc-pd-hero:after{content:"";position:absolute;pointer-events:none}.dcc-pd-hero:before{right:-30px;top:-70px;width:235px;height:235px;border:1px solid rgba(240,201,107,.16);border-radius:50%}.dcc-pd-hero:after{right:-55px;top:18px;width:250px;height:1px;transform:rotate(-27deg);background:linear-gradient(90deg,transparent,rgba(240,201,107,.50),transparent)}
      .dcc-pd-kicker{position:relative;z-index:2;color:${GOLD2};font-size:9.5px;font-weight:850;letter-spacing:3px;text-transform:uppercase}.dcc-pd-title{position:relative;z-index:2;margin:22px 0 0;max-width:76%;font-family:-apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",Arial,sans-serif;font-size:28px;line-height:1.02;font-weight:780;letter-spacing:-.7px;color:#f7f5f0}.dcc-pd-title span{display:block;margin-top:4px;color:${GOLD2};font-weight:820}.dcc-pd-title:after{content:"";display:block;width:46px;height:2px;margin-top:13px;border-radius:99px;background:linear-gradient(90deg,${GOLD2},rgba(217,170,74,.35))}.dcc-pd-caption{position:relative;z-index:2;margin-top:11px;color:#8f98a3;font-size:10.5px;line-height:1.35}

      .dcc-pd-strip{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin:10px 0 0}.dcc-pd-stat{min-height:79px;padding:12px 10px;border:1px solid rgba(217,170,74,.30);border-radius:17px;background:linear-gradient(145deg,#10151a,#090c0f);box-shadow:inset 0 1px 0 rgba(255,255,255,.025)}.dcc-pd-stat strong{display:block;font-size:24px;line-height:1;color:#f7f5f1;letter-spacing:-.5px}.dcc-pd-stat span{display:block;margin-top:10px;color:#8f97a2;font-size:7px;line-height:1.28;letter-spacing:.75px;text-transform:uppercase}

      .dcc-pd-section{margin-top:10px;padding:14px 15px;border:1px solid rgba(217,170,74,.38);border-radius:20px;background:radial-gradient(circle at 96% 0,rgba(217,170,74,.06),transparent 29%),linear-gradient(145deg,#10151a,#080b0e);box-shadow:inset 0 1px 0 rgba(255,255,255,.025)}.dcc-pd-section-kicker{color:${GOLD2};font-size:9.5px;font-weight:850;letter-spacing:2.6px;text-transform:uppercase}.dcc-pd-section-sub{margin-top:5px;color:#7f8893;font-size:9px;line-height:1.35}
      .dcc-pd-row{width:100%;display:grid;grid-template-columns:40px minmax(0,1fr) auto 15px;align-items:center;gap:10px;padding:11px 0;border:0;border-top:1px solid rgba(255,255,255,.08);background:none;color:#f5f2ec;text-align:left;-webkit-tap-highlight-color:transparent}.dcc-pd-row:first-of-type{margin-top:8px}.dcc-pd-icon{width:38px;height:38px;display:grid;place-items:center;border:1px solid rgba(217,170,74,.32);border-radius:12px;color:${GOLD2};font-size:17px;background:rgba(217,170,74,.025)}.dcc-pd-copy{min-width:0}.dcc-pd-copy b{display:block;font-size:12.5px;line-height:1.15}.dcc-pd-copy span{display:block;margin-top:4px;font-size:9.5px;color:#8d96a1;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.dcc-pd-badge{padding:6px 8px;border-radius:10px;font-size:7px;font-weight:800;color:${GOLD2};border:1px solid rgba(217,170,74,.30);background:rgba(217,170,74,.025)}.dcc-pd-arrow{color:${GOLD2};font-size:18px}
      .dcc-pd-empty-ok{display:flex;align-items:center;gap:10px;padding:12px 0 2px;color:#aeb4bc;font-size:11px}.dcc-ok-icon{width:34px;height:34px;flex:none;border:1px solid rgba(217,170,74,.40);border-radius:11px;display:grid;place-items:center;color:${GOLD2};background:rgba(217,170,74,.03)}

      .dcc-pd-banner{position:relative;overflow:hidden;min-height:72px;margin-top:10px;padding:15px 16px;border:1px solid rgba(217,170,74,.42);border-radius:20px;background:linear-gradient(120deg,#0e1216,#090c0f 60%,#171207)}.dcc-pd-banner:after{content:"";position:absolute;right:-34px;top:-46px;width:128px;height:150px;transform:rotate(30deg);background:linear-gradient(90deg,transparent,rgba(240,201,107,.09),transparent)}.dcc-pd-banner small{display:block;color:#a98b4c;font-size:7px;letter-spacing:2.2px;text-transform:uppercase}.dcc-pd-banner strong{display:block;margin-top:6px;color:#f2eee7;font-size:15px;letter-spacing:.1px;font-weight:650}

      .dcc-cl{padding-top:14px}.dcc-cl-head{display:flex;align-items:flex-start;justify-content:space-between;gap:14px;margin:6px 2px 20px}.dcc-cl-head h1{margin:0;font-size:34px;letter-spacing:-1.3px}.dcc-cl-head p{margin:6px 0 0;color:#939aa5;font-size:14px}.dcc-cl-new{border:1px solid #f0c96b;border-radius:15px;padding:12px 16px;background:linear-gradient(135deg,#f0c96b,#d9aa4a);color:#090909;font-weight:800;font-size:12px;white-space:nowrap}
      .dcc-cl-tools{display:grid;grid-template-columns:1fr 48px;gap:9px}.dcc-cl-search{height:48px;display:flex;align-items:center;gap:10px;padding:0 15px;border:1px solid #333942;border-radius:15px;background:linear-gradient(145deg,#0e1318,#080b0e);color:#8f97a3}.dcc-cl-search input{width:100%;border:0;outline:0;background:none;color:#f5f5f5;font:inherit}.dcc-cl-filter{border:1px solid #333942;border-radius:15px;background:#0d1115;color:#a9b0ba;font-size:19px}
      .dcc-cl-subtools{display:flex;justify-content:space-between;align-items:center;margin:11px 0 14px}.dcc-cl-tabs{display:flex;border:1px solid #292f36;border-radius:22px;overflow:hidden;background:#090c0f}.dcc-cl-tab{padding:9px 18px;border:0;background:none;color:#9aa1ac;font-size:11px}.dcc-cl-tab.active{border:1px solid ${GOLD2};border-radius:21px;background:radial-gradient(circle at 50% 50%,#d9aa4a35,#15100a);color:${GOLD2};box-shadow:0 0 18px #d9aa4a28}.dcc-cl-sort{padding:9px 13px;border:1px solid #343941;border-radius:15px;background:#0a0d10;color:#e8e8e8;font-size:11px}
      .dcc-cl-list{display:grid;gap:9px}.dcc-cl-card{display:grid;grid-template-columns:minmax(0,1fr) minmax(135px,.85fr) 112px;align-items:center;gap:13px;min-height:104px;padding:14px 15px;border:1px solid rgba(217,170,74,.58);border-radius:17px;background:radial-gradient(ellipse at 86% 35%,rgba(217,170,74,.08),transparent 23%),linear-gradient(120deg,#0c1014,#080b0e);box-shadow:0 10px 26px #0005}.dcc-cl-info{min-width:0}.dcc-cl-name{font-size:17px;font-weight:800;color:#f5f3ef}.dcc-cl-goal{margin-top:6px;color:${GOLD2};font-size:12px}.dcc-cl-weight{margin-top:4px;color:#a4abb5;font-size:12px}.dcc-cl-training{padding-left:14px;border-left:1px solid #343a42}.dcc-cl-tr-title{display:flex;align-items:center;gap:7px;color:#f1f1ef;font-size:10px}.dcc-cl-dumbbell{color:${GOLD2};font-size:18px}.dcc-cl-progress{display:flex;align-items:center;gap:8px;margin-top:8px}.dcc-cl-track{height:6px;flex:1;border-radius:8px;background:#2a3037;overflow:hidden}.dcc-cl-fill{height:100%;border-radius:8px;background:linear-gradient(90deg,#d9aa4a,#f0c96b)}.dcc-cl-pct{font-size:11px}.dcc-cl-manage{min-height:48px;border:1px solid ${GOLD2};border-radius:13px;background:linear-gradient(145deg,#18140c,#0a0b0c);color:${GOLD2};font-size:11px;font-weight:800;line-height:1.25}

      #coach .side{height:62px!important;left:14px!important;right:14px!important;bottom:10px!important;border-radius:21px!important;padding:0 7px!important}
      #coach-nav{display:grid!important;grid-template-columns:repeat(5,minmax(0,1fr))!important;gap:0!important;height:100%!important}
      #coach-nav button{height:100%!important;padding:5px 2px!important;font-size:8px!important;transition:none!important;transform:none!important}#coach-nav button svg{width:21px!important;height:21px!important}#coach-nav button span{font-size:7.3px!important;margin-top:2px!important}

      @media(max-width:600px){.dcc-pd-title{font-size:26px}.dcc-pd-strip{grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.dcc-pd-stat{min-height:72px}.dcc-pd-stat strong{font-size:22px}.dcc-pd-stat span{font-size:7px}.dcc-cl-head h1{font-size:31px}.dcc-cl-head p{font-size:12px}.dcc-cl-new{padding:11px 13px}.dcc-cl-card{grid-template-columns:minmax(0,1fr) minmax(108px,.8fr) 88px;gap:9px;padding:12px 11px;min-height:94px}.dcc-cl-name{font-size:15px}.dcc-cl-goal,.dcc-cl-weight{font-size:10.5px}.dcc-cl-training{padding-left:9px}.dcc-cl-manage{font-size:9.5px;padding:5px}.dcc-cl-tab{padding:8px 13px}}
    `;
    document.head.appendChild(s);
  }

  function daysSince(v){if(!v)return null;const d=new Date(v);return Number.isFinite(d.getTime())?Math.floor((Date.now()-d.getTime())/86400000):null}
  function latestWorkout(id){const h=data?.workoutHistory?.[id]||[];return h.slice().sort((a,b)=>new Date(b.date)-new Date(a.date))[0]||null}
  function hasRoutine(id){return Array.isArray(data?.routines?.[id])&&data.routines[id].length>0}
  function pendingCheck(c){const x=data?.checkins?.[c.id];return !!(x?.sentAt&&!x?.reviewed)}
  function trainingProgress(c){const r=data?.routines?.[c.id];if(!Array.isArray(r)||!r.length)return 0;const h=data?.workoutHistory?.[c.id]||[];if(!h.length)return 0;const recent=h.filter(x=>{const d=daysSince(x.date);return d!==null&&d<=30}).length;return Math.min(100,Math.round(recent/Math.max(1,r.length*4)*100))}

  function taskRow(i){return `<button class="dcc-pd-row" onclick="${i.action}"><span class="dcc-pd-icon">${i.icon}</span><span class="dcc-pd-copy"><b>${esc(i.title)}</b><span>${esc(i.text)}</span></span><span class="dcc-pd-badge">${esc(i.badge)}</span><span class="dcc-pd-arrow">›</span></button>`}

  function renderDashboard(){
    injectCss();const main=document.getElementById("coach-main");if(!main)return;main.className="dcc-premium-dashboard";
    const cs=data?.clients||[],tasks=[],attention=[];
    cs.forEach(c=>{if(pendingCheck(c))tasks.push({icon:"✓",title:"REVISAR CHECK-IN",text:c.name,badge:"HOY",action:`reviewCheckin('${c.id}')`});if(!hasRoutine(c.id))tasks.push({icon:"＋",title:"ASIGNAR RUTINA",text:c.name,badge:"PENDIENTE",action:`openClient('${c.id}')`});const gap=daysSince(latestWorkout(c.id)?.date);if(gap!==null&&gap>=7)attention.push({icon:"!",title:c.name,text:`${gap} DÍAS SIN REGISTRAR ENTRENAMIENTO`,badge:"SEGUIMIENTO",action:`openClient('${c.id}')`})});
    const hr=new Date().getHours(),g=hr<13?"BUENOS DÍAS":hr<20?"BUENAS TARDES":"BUENAS NOCHES";
    main.innerHTML=`<div class="dcc-pd"><section class="dcc-pd-hero"><div class="dcc-pd-kicker">PANEL DE ENTRENADOR</div><h1 class="dcc-pd-title">${g},<span>DANIEL</span></h1><div class="dcc-pd-caption">Clientes, seguimiento y próximas acciones.</div></section><div class="dcc-pd-strip"><div class="dcc-pd-stat"><strong>${cs.length}</strong><span>CLIENTES</span></div><div class="dcc-pd-stat"><strong>${cs.filter(pendingCheck).length}</strong><span>CHECK-IN PENDIENTES</span></div><div class="dcc-pd-stat"><strong>0</strong><span>RUTINAS POR RENOVAR</span></div><div class="dcc-pd-stat"><strong>0</strong><span>DIETAS POR RENOVAR</span></div></div><section class="dcc-pd-section"><div class="dcc-pd-section-kicker">TAREAS PENDIENTES</div><div class="dcc-pd-section-sub">ACCIONES QUE REQUIEREN TU ATENCIÓN</div>${tasks.length?tasks.slice(0,6).map(taskRow).join(""):`<div class="dcc-pd-empty-ok"><div class="dcc-ok-icon">✓</div><span>Todo al día. No hay tareas pendientes.</span></div>`}</section><section class="dcc-pd-section"><div class="dcc-pd-section-kicker">REQUIEREN ATENCIÓN</div><div class="dcc-pd-section-sub">SEÑALES DE SEGUIMIENTO DETECTADAS AUTOMÁTICAMENTE</div>${attention.length?attention.slice(0,6).map(taskRow).join(""):'<div class="dcc-pd-empty-ok"><div class="dcc-ok-icon">✓</div><span>Sin alertas de seguimiento.</span></div>'}</section><section class="dcc-pd-banner"><small>CADA CLIENTE ES UN PROCESO.</small><strong>Tú marcas la diferencia.</strong></section></div>`;
  }

  function clientCard(c){const p=trainingProgress(c),goal=c.goal||c.objective||c.objetivo||"Objetivo por definir",weight=c.weight||c.peso||"";return `<article class="dcc-cl-card" data-name="${esc(c.name).toLowerCase()}" data-pending="${pendingCheck(c)?"1":"0"}"><div class="dcc-cl-info"><div class="dcc-cl-name">${esc(c.name)}</div><div class="dcc-cl-goal">${esc(goal)}</div>${weight?`<div class="dcc-cl-weight">${esc(weight)} kg</div>`:""}</div><div class="dcc-cl-training"><div class="dcc-cl-tr-title"><span class="dcc-cl-dumbbell">⌁</span> Entrenamiento</div><div class="dcc-cl-progress"><div class="dcc-cl-track"><div class="dcc-cl-fill" style="width:${p}%"></div></div><span class="dcc-cl-pct">${p}%</span></div></div><button class="dcc-cl-manage" onclick="openClient('${c.id}')">Gestionar<br>cliente</button></article>`}

  function renderClients(){injectCss();const main=document.getElementById("coach-main");if(!main)return;main.className="dcc-premium-clients";const cs=data?.clients||[];main.innerHTML=`<div class="dcc-cl"><header class="dcc-cl-head"><div><h1>Clientes</h1><p>Gestiona el proceso de cada persona.</p></div><button class="dcc-cl-new" onclick="newClient()">＋ Nuevo cliente</button></header><div class="dcc-cl-tools"><label class="dcc-cl-search">⌕<input id="dccClientSearch" placeholder="Buscar cliente..." oninput="window.dccFilterClients()"></label><button class="dcc-cl-filter" onclick="toast('Filtros próximamente')">▽</button></div><div class="dcc-cl-subtools"><div class="dcc-cl-tabs"><button class="dcc-cl-tab active" onclick="window.dccClientTab('all',this)">Todos</button><button class="dcc-cl-tab" onclick="window.dccClientTab('pending',this)">Pendientes por revisar</button></div><button class="dcc-cl-sort" onclick="window.dccSortClients()">↕ &nbsp; A-Z⌄</button></div><div class="dcc-cl-list" id="dccClientList">${cs.map(clientCard).join("")||'<div class="dcc-cl-empty">Todavía no hay clientes.</div>'}</div></div>`;window.__dccClientMode="all";window.__dccClientSort="az"}

  window.dccFilterClients=function(){const q=(document.getElementById("dccClientSearch")?.value||"").toLowerCase();document.querySelectorAll(".dcc-cl-card").forEach(x=>x.style.display=(x.dataset.name.includes(q)&&(window.__dccClientMode!=="pending"||x.dataset.pending==="1"))?"grid":"none")};
  window.dccClientTab=function(m,b){window.__dccClientMode=m;document.querySelectorAll(".dcc-cl-tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");window.dccFilterClients()};
  window.dccSortClients=function(){const l=document.getElementById("dccClientList");if(!l)return;window.__dccClientSort=window.__dccClientSort==="az"?"za":"az";[...l.querySelectorAll(".dcc-cl-card")].sort((a,b)=>window.__dccClientSort==="az"?a.dataset.name.localeCompare(b.dataset.name):b.dataset.name.localeCompare(a.dataset.name)).forEach(x=>l.appendChild(x))};

  function svg(i){return {panel:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="4" y="4" width="6" height="6" rx="1"/><rect x="14" y="4" width="6" height="6" rx="1"/><rect x="4" y="14" width="6" height="6" rx="1"/><rect x="14" y="14" width="6" height="6" rx="1"/></svg>',clients:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="9" cy="8" r="3"/><circle cx="17" cy="9" r="2.5"/><path d="M3.5 20c.5-4 2.3-6 5.5-6s5 2 5.5 6"/></svg>',calendar:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="4" y="5" width="16" height="15" rx="2"/><path d="M8 3v4M16 3v4M4 10h16"/></svg>',check:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="5" y="4" width="14" height="17" rx="2"/><path d="M8 11l2 2 5-5M8 17h7"/></svg>',msg:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M20 11.5a7.5 7.5 0 0 1-8 7.5 8.7 8.7 0 0 1-4-.9L4 20l1.4-3.4A7.3 7.3 0 0 1 4 11.5 7.5 7.5 0 0 1 12 4a7.5 7.5 0 0 1 8 7.5Z"/></svg>'}[i]||""}
  function navHtml(){return `<button onclick="showCoach('dashboard')">${svg("panel")}<span>Panel</span></button><button onclick="showCoach('clients')">${svg("clients")}<span>Clientes</span></button><button onclick="toast('Calendario próximamente')">${svg("calendar")}<span>Calendario</span></button><button onclick="showCoach('checkins')">${svg("check")}<span>Check-in</span></button><button onclick="showCoach('messages')">${svg("msg")}<span>Mensajes</span></button>`}
  function enforceNav(){const n=document.getElementById("coach-nav");if(!n)return;const wanted=["Panel","Clientes","Calendario","Check-in","Mensajes"],labels=[...n.querySelectorAll("button span")].map(x=>x.textContent.trim());if(labels.length!==5||wanted.some((x,i)=>labels[i]!==x))n.innerHTML=navHtml();n.style.setProperty("grid-template-columns","repeat(5,minmax(0,1fr))","important")}
  function active(screen){const n=document.getElementById("coach-nav");if(!n)return;const map={dashboard:0,clients:1,checkins:3,messages:4};n.querySelectorAll("button").forEach(x=>x.classList.remove("active"));const i=map[screen];if(i!==undefined)n.querySelectorAll("button")[i]?.classList.add("active")}
  function lockNav(){enforceNav();if(typeof window.buildCoachNav==="function"&&!window.buildCoachNav.__dccLocked){const old=window.buildCoachNav;const wrapped=function(){const r=old.apply(this,arguments);requestAnimationFrame(enforceNav);return r};wrapped.__dccLocked=true;window.buildCoachNav=wrapped}}

  function install(){injectCss();lockNav();const original=window.showCoach;if(typeof original!=="function"||original.__dccPremiumV6)return;const wrapped=function(screen){if(screen==="dashboard"){window.currentScreen=screen;renderDashboard();enforceNav();active(screen);return}if(screen==="clients"){window.currentScreen=screen;renderClients();enforceNav();active(screen);return}const main=document.getElementById("coach-main");if(main)main.classList.remove("dcc-premium-dashboard","dcc-premium-clients");const r=original.apply(this,arguments);requestAnimationFrame(()=>{enforceNav();active(screen)});return r};wrapped.__dccPremiumV6=true;wrapped.__original=original;window.showCoach=wrapped}

  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>setTimeout(install,0),{once:true});else setTimeout(install,0);
  window.addEventListener("load",()=>setTimeout(install,30),{once:true});
})();