/* DCC — Progreso premium del cliente */
(function(){
const G='#f2c85f', esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>{const n=parseFloat(String(v??'').replace(',','.'));return Number.isFinite(n)?n:null};
const fmt=(v,d=1)=>v==null?'—':Number(v).toFixed(d).replace('.',',');
function addCss(){if(document.getElementById('dcc-progress-premium-css'))return;const s=document.createElement('style');s.id='dcc-progress-premium-css';s.textContent=`
.dcc-p-metric{position:relative;overflow:hidden}.dcc-p-spark{height:25px;margin-top:7px}.dcc-p-spark svg{width:100%;height:100%;overflow:visible}.dcc-p-good{color:#52e39a!important}.dcc-p-bad{color:#ff5a62!important}.dcc-p-section{margin-top:12px;padding:16px;border:1px solid rgba(224,173,76,.55);border-radius:20px;background:linear-gradient(145deg,#0e1418,#070b0e)}.dcc-p-head{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:12px}.dcc-p-head h2{margin:0;font-size:20px}.dcc-p-head p{margin:4px 0 0;color:#8e98a3;font-size:10px}.dcc-p-tabs{display:flex;gap:5px}.dcc-p-tabs button{border:1px solid #303942;border-radius:999px;background:#090e12;color:#a7afb9;padding:8px 13px;font-size:9px;font-weight:800}.dcc-p-tabs button.active{border-color:${G};background:${G};color:#0a0906}.dcc-p-chart{height:190px;position:relative}.dcc-p-chart svg{width:100%;height:100%;overflow:visible}.dcc-p-empty{height:150px;display:grid;place-items:center;color:#818b96;font-size:11px;text-align:center}.dcc-p-force-head{display:flex;align-items:center;justify-content:space-between}.dcc-p-all{border:1px solid #b8872c;border-radius:999px;background:#090d10;color:${G};padding:9px 13px;font-size:9px;font-weight:850}.dcc-p-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:7px;margin-top:11px}.dcc-p-ex{min-width:0;padding:9px;border:1px solid #29333b;border-radius:14px;background:#0a1014}.dcc-p-ex-top{display:flex;gap:8px;align-items:center}.dcc-p-ex img{width:45px;height:45px;object-fit:contain;border-radius:9px;background:#efefec}.dcc-p-ex b{font-size:10px;line-height:1.2}.dcc-p-change{display:block;margin-top:7px;font-size:12px;font-weight:900;color:#52e39a}.dcc-p-change.down{color:#ff5a62}.dcc-p-detail{display:block;margin-top:5px;color:#c0c7cf;font-size:9px;line-height:1.45}.dcc-p-mini{height:22px;margin-top:7px}.dcc-p-mini svg{width:100%;height:100%}.dcc-p-more{display:none}.dcc-p-grid.show-all .dcc-p-more{display:block}.dcc-p-note{margin-top:8px;color:#76818c;font-size:8px}.dcc-p-range{border:1px solid #303942;border-radius:999px;background:#090e12;color:#b8c0c9;padding:8px 11px;font-size:9px}
@media(max-width:650px){.dcc-p-section{padding:13px}.dcc-p-head{align-items:flex-start;flex-direction:column}.dcc-p-tabs{width:100%}.dcc-p-tabs button{flex:1;padding:8px 5px}.dcc-p-chart{height:165px}.dcc-p-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.dcc-p-force-head{align-items:flex-start}.dcc-p-ex img{width:40px;height:40px}}
`;document.head.appendChild(s)}
function weightPoints(id,cl){const a=Array.isArray(data?.weights?.[id])?data.weights[id]:[];let out=a.map((x,i)=>({v:num(typeof x==='object'?(x.weight??x.value??x.peso):x),date:typeof x==='object'?(x.date??x.created_at??x.createdAt??x.fecha):null,i})).filter(x=>x.v!=null);if(!out.length){const v=num(cl?.initial??cl?.weight);if(v!=null)out=[{v,date:null,i:0}]}return out}
function fatPoints(id,cl){const out=[],seen=new Set(),push=(v,date)=>{v=num(v);if(v==null||v<2||v>70)return;const k=String(date||'')+'|'+v;if(!seen.has(k)){seen.add(k);out.push({v,date:date||null})}};['bodyFat','body_fat','fat','fatPct','fat_pct','grasa','porcentajeGrasa'].forEach(k=>push(cl?.[k],cl?.updated_at));const walk=(o,d=0)=>{if(!o||d>5)return;if(Array.isArray(o))return o.forEach(x=>walk(x,d+1));if(typeof o!=='object')return;const cid=o.client_id??o.clientId??o.client,ok=cid==null||String(cid)===String(id),date=o.date??o.created_at??o.createdAt??o.fecha;Object.entries(o).forEach(([k,v])=>{if(ok&&/fat|grasa/i.test(k)&&!/free/i.test(k))push(v,date);if(v&&typeof v==='object')walk(v,d+1)})};['checkins','checkIns','checkinHistory','progress','measurements'].forEach(k=>walk(data?.[k]));return out}
function sessions(id){const raw=data?.workoutHistory?.[id];return Array.isArray(raw)?raw:[]}
function lib(ex){const L=Array.isArray(window.exerciseLibraryFull)?window.exerciseLibraryFull:[],id=String(ex?.id??ex?.exerciseId??ex?.exercise_id??''),n=String(ex?.name??ex?.nombre??ex?.exercise??ex?.exerciseName??'').toLowerCase();return L.find(x=>id&&String(x.id)===id)||L.find(x=>String(x.name||'').toLowerCase()===n)}
function exerciseName(ex){return ex?.name??ex?.nombre??ex?.exerciseName??ex?.exercise??lib(ex)?.name??'Ejercicio'}
function exerciseKey(ex){return String(ex?.id??ex?.exerciseId??ex?.exercise_id??exerciseName(ex)).toLowerCase()}
function setPairs(ex){let sets=ex?.sets??ex?.series??ex?.completedSets??ex?.setData;if(!Array.isArray(sets))sets=[];let p=sets.map(s=>({w:num(s?.weight??s?.kg??s?.peso??s?.load),r:num(s?.reps??s?.repetitions??s?.repeticiones)})).filter(x=>x.w!=null&&x.r!=null&&x.w>=0&&x.r>0);if(!p.length){const w=num(ex?.weight??ex?.kg??ex?.peso??ex?.load),r=num(ex?.reps??ex?.repetitions??ex?.repeticiones);if(w!=null&&r!=null)p=[{w,r}]}return p}
function collectExercises(o,arr=[],depth=0){if(!o||depth>6)return arr;if(Array.isArray(o)){o.forEach(x=>collectExercises(x,arr,depth+1));return arr}if(typeof o!=='object')return arr;if(setPairs(o).length&&(o.name||o.nombre||o.exercise||o.exerciseName||o.exerciseId||o.exercise_id))arr.push(o);Object.entries(o).forEach(([k,v])=>{if(v&&typeof v==='object'&&!['client','user'].includes(k))collectExercises(v,arr,depth+1)});return arr}
function forceData(id){const map=new Map();sessions(id).forEach((s,si)=>{const date=s?.date??s?.created_at??s?.createdAt??s?.fecha??null;const uniq=new Set();collectExercises(s).forEach(ex=>{const key=exerciseKey(ex);if(uniq.has(key))return;uniq.add(key);const pairs=setPairs(ex);if(!pairs.length)return;const best=pairs.reduce((a,x)=>{const e=x.w*(1+x.r/30);return e>a.e?{...x,e}:a},{e:-1});if(!map.has(key))map.set(key,{key,name:exerciseName(ex),image:lib(ex)?.image||'',points:[]});map.get(key).points.push({...best,date,si})})});return [...map.values()].map(x=>{x.points.sort((a,b)=>a.si-b.si);const a=x.points[0],b=x.points[x.points.length-1];x.change=x.points.length>1&&a.e>0?(b.e/a.e-1)*100:null;x.first=a;x.last=b;return x}).sort((a,b)=>(Math.abs(b.change||0)-Math.abs(a.change||0)))}
function globalForce(fd){const c=fd.map(x=>x.change).filter(x=>x!=null&&Number.isFinite(x));if(!c.length)return null;c.sort((a,b)=>a-b);const m=Math.floor(c.length/2);return c.length%2?c[m]:(c[m-1]+c[m])/2}
function path(vals,w=280,h=70,p=5){if(vals.length<2)return'';const lo=Math.min(...vals),hi=Math.max(...vals),span=hi-lo||1;return vals.map((v,i)=>`${i?'L':'M'}${p+i*(w-2*p)/(vals.length-1)},${h-p-(v-lo)*(h-2*p)/span}`).join(' ')}
function spark(vals,downGood=false){if(vals.length<2)return'';const d=path(vals);return`<div class="dcc-p-spark"><svg viewBox="0 0 280 70" preserveAspectRatio="none"><path d="${d}" fill="none" stroke="${G}" stroke-width="3" vector-effect="non-scaling-stroke"/><path d="${d} L275,68 L5,68 Z" fill="rgba(242,200,95,.08)"/></svg></div>`}
function chart(points,label){const vals=points.map(x=>x.v);if(vals.length<2)return`<div class="dcc-p-empty">Todavía no hay suficientes registros de ${label.toLowerCase()} para dibujar una evolución.</div>`;const d=path(vals,800,180,12),dots=vals.map((v,i)=>{const lo=Math.min(...vals),hi=Math.max(...vals),span=hi-lo||1,x=12+i*776/(vals.length-1),y=168-(v-lo)*156/span;return`<circle cx="${x}" cy="${y}" r="4" fill="${G}"/><text x="${x}" y="${Math.max(12,y-9)}" text-anchor="middle" fill="#c9d0d6" font-size="10">${fmt(v)}</text>`}).join('');return`<div class="dcc-p-chart"><svg viewBox="0 0 800 180" preserveAspectRatio="none"><line x1="12" y1="168" x2="788" y2="168" stroke="#273039"/><path d="${d}" fill="none" stroke="${G}" stroke-width="3" vector-effect="non-scaling-stroke"/>${dots}</svg></div>`}
function exCard(x,i){const ch=x.change,cls=ch!=null&&ch<0?'down':'',sign=ch==null?'':ch>=0?'↗ +':'↘ ';const vals=x.points.map(p=>p.e);return`<article class="dcc-p-ex ${i>=4?'dcc-p-more':''}"><div class="dcc-p-ex-top">${x.image?`<img src="${esc(x.image)}" alt="">`:''}<b>${esc(x.name)}</b></div><span class="dcc-p-change ${cls}">${ch==null?'Sin comparación':sign+fmt(ch)+' %'}</span><span class="dcc-p-detail">${fmt(x.first.w)} kg × ${fmt(x.first.r,0)}<br>→ ${fmt(x.last.w)} kg × ${fmt(x.last.r,0)}</span>${vals.length>1?`<div class="dcc-p-mini"><svg viewBox="0 0 280 70" preserveAspectRatio="none"><path d="${path(vals)}" fill="none" stroke="${ch<0?'#ff5a62':G}" stroke-width="3" vector-effect="non-scaling-stroke"/></svg></div>`:''}</article>`}
function renderProgress(id){const cl=(data?.clients||[]).find(x=>String(x.id)===String(id));if(!cl)return;const root=document.querySelector('#coach-main .dcc-ca-wrap');if(!root)return;const wp=weightPoints(id,cl),fp=fatPoints(id,cl),fd=forceData(id),gf=globalForce(fd),wi=wp[0]?.v,wc=wp.at(-1)?.v,fi=fp[0]?.v,fc=fp.at(-1)?.v;const metrics=root.querySelector('.dcc-ca-metrics');if(metrics){const delta=(cur,ini,u,goodDown=true)=>cur==null||ini==null?'Sin histórico':`${cur-ini>0?'↑':'↓'} ${fmt(Math.abs(cur-ini))} ${u} desde el inicio`;metrics.innerHTML=`<div class="dcc-ca-metric dcc-p-metric"><small>Peso actual</small><b>${wc!=null?fmt(wc)+' kg':'—'}</b><span class="dcc-ca-trend ${wc!=null&&wi!=null&&wc<wi?'good':''}">${delta(wc,wi,'kg')}</span>${spark(wp.map(x=>x.v))}</div><div class="dcc-ca-metric dcc-p-metric"><small>% de grasa</small><b>${fc!=null?fmt(fc)+' %':'—'}</b><span class="dcc-ca-trend ${fc!=null&&fi!=null&&fc<fi?'good':''}">${delta(fc,fi,'%')}</span>${spark(fp.map(x=>x.v))}</div><div class="dcc-ca-metric dcc-p-metric"><small>Fuerza global</small><b>${gf==null?'—':(gf>=0?'+':'')+fmt(gf)+' %'}</b><span class="dcc-ca-trend ${gf!=null&&gf>=0?'good':''}">${gf==null?'Sin datos suficientes':'Evolución desde el inicio'}</span>${spark(fd.filter(x=>x.change!=null).map(x=>x.change))}</div>`}
const host=root.querySelector('.dcc-ca-tabs')?.nextElementSibling;if(!host)return;window.__dccProgressMetric=window.__dccProgressMetric||'weight';const metric=window.__dccProgressMetric, pts=metric==='fat'?fp:metric==='force'?fd.filter(x=>x.change!=null).map((x,i)=>({v:x.change,i})):wp, label=metric==='fat'?'% Grasa':metric==='force'?'Fuerza':'Peso';host.innerHTML=`<section class="dcc-p-section"><div class="dcc-p-head"><div><h2>Evolución</h2><p>Visualiza el progreso a lo largo del tiempo.</p></div><div class="dcc-p-tabs"><button class="${metric==='weight'?'active':''}" onclick="dccProgressMetric('${id}','weight')">Peso</button><button class="${metric==='fat'?'active':''}" onclick="dccProgressMetric('${id}','fat')">% Grasa</button><button class="${metric==='force'?'active':''}" onclick="dccProgressMetric('${id}','force')">Fuerza</button></div></div>${chart(pts,label)}</section><section class="dcc-p-section"><div class="dcc-p-force-head"><div><h2 style="margin:0;font-size:20px">Progreso de fuerza</h2><p style="margin:4px 0 0;color:#8e98a3;font-size:10px">Evolución en sus ejercicios registrados.</p></div>${fd.length>4?`<button class="dcc-p-all" onclick="dccProgressAll(this)">Ver todos ›</button>`:''}</div>${fd.length?`<div class="dcc-p-grid">${fd.map(exCard).join('')}</div><div class="dcc-p-note">La evolución combina carga y repeticiones mediante fuerza estimada. Solo se comparan ejercicios con registros disponibles.</div>`:`<div class="dcc-p-empty">Cuando el cliente registre cargas y repeticiones en sus entrenamientos, aquí aparecerá su progreso de fuerza.</div>`}</section>`}
window.dccProgressMetric=(id,m)=>{window.__dccProgressMetric=m;renderProgress(id)};window.dccProgressAll=b=>{const g=b.closest('.dcc-p-section').querySelector('.dcc-p-grid');g.classList.toggle('show-all');b.textContent=g.classList.contains('show-all')?'Ver menos ‹':'Ver todos ›'}
}
function install(){addCss();const old=window.dccClientAdmin;if(typeof old!=='function'||old.__dccProgress)return setTimeout(install,100);const fn=function(id,tab){old(id,tab);if(tab==='progress')setTimeout(()=>renderProgress(id),0)};fn.__dccProgress=true;fn.__base=old;window.dccClientAdmin=fn}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(install,150));else setTimeout(install,150);
})();